Review 1 - 13.01.24
georgyshamteev/neuralnetwork pull request #1
Opened 2024-01-13 15:55 UTC by georgyshamteev

2024-01-13 17:41 UTC, DimaTrushin requested changes
Сделал несколько мелких замечаний. Обрати внимение, что если какая-то ошибка встречалась несколько раз я не повторял комментарий. Я ожидаю, что ты по аналогии исправишь все остальные места.

2024-01-13 17:41 UTC, DimaTrushin commented on .clang-format
> +InsertNewlineAtEOF: true
Кирпичи! Добавляй обязательно пустую строку в конце каждого файла. Это требование гита. Иначе он ругается и пользователи будут видеть сообщения об этих ошибках при клонировании. Не надо так делать.

2024-01-13 17:41 UTC, DimaTrushin commented on CMakeLists.txt
> +
Этого не достаточно, добавь
```cpp
set(CMAKE_CXX_STANDARD_REQUIRED ON)
```
Иначе вообще говоря строчка выше ничего не гарантирует.

2024-01-13 17:41 UTC, DimaTrushin commented on NeuralNetwork/activation.h
> +    ////
Это ты руками ставишь или это у тебя какие-то автоматические настройки? Лучше код не захламлять подобными вещами. Да бывают ситуации, когда нужно разграничивать код комментариями, но обычно это в метопрограммировании встречается, где тупо просто по-другому никак. А в обычном коде лучше вообще избегать ненужных закомментированных строк.

2024-01-13 17:41 UTC, DimaTrushin commented on NeuralNetwork/activation.h
> +    Tensor2D operator()(Tensor2D x);
Почему оператор не константный? Он меняет состояние?

2024-01-13 17:41 UTC, DimaTrushin commented on NeuralNetwork/activation.h
> +    void Update(Tensor2D u);
Если принимаешь by value, не забудь мувнуть из аргумента.

2024-01-13 17:41 UTC, DimaTrushin commented on NeuralNetwork/activation.h
> +};
Заинтриговал имплементацией.

2024-01-13 17:41 UTC, DimaTrushin commented on NeuralNetwork/linear.h
> +#include "../EigenRand/EigenRand/EigenRand"
Добавсь в include_directory нужный путь до EigenRand, чтобы подключать просто
```cpp
#include "EigenRand/EigenRand"
```

2024-01-13 17:41 UTC, DimaTrushin commented on NeuralNetwork/linear.h
> +    Linear() = delete;
Это писать не обязательно, потому что у тебя уже есть другой конструктор. Он автоматом отключает генерацию дефолтного.

2024-01-13 17:41 UTC, DimaTrushin commented on NeuralNetwork/linear.h
> +    Tensor2D output_seq_;
Не уверен, что это надо хранить. Потому что в последовательных слоях у тебя эти данные будут храниться дважды. Инпут следующего слоя можно всегда считать из следующего слоя.

2024-01-13 17:41 UTC, DimaTrushin commented on NeuralNetwork/linear.h
> +    Linear(size_t in_features, size_t out_features, bool bias = true);
Плохо делать size_t в виде типа для размеров. Дело в том, что Eigen использует тип под псевдонимом Eigen::Index. И он более или менее в ближайшие несколько сотен тысяч лет обещает быть int. Я бы рекомендовал вообще не пользоваться сырыми типами и добавил бы юзинги вида
```cpp
using Index = Eigen::Index;
```
И везде пользовался бы им для размеров.

2024-01-13 17:41 UTC, DimaTrushin commented on NeuralNetwork/linear.h
> +    Linear(size_t in_features, size_t out_features, bool bias = true);
Плохой интерфейс. Ну какой смысл у аргумента bias? Вот что значит что он true? Если тебе нужны флаги, то делай enum class и в нем задавай нормальные имена для констант. Переделай через enum class.

2024-01-13 17:41 UTC, DimaTrushin commented on NeuralNetwork/linear.cpp
> +    Eigen::Rand::UniformRealGen gen(-sqrt_k, sqrt_k);
Это нарушение уровня абстракции. Ты по сути тут задаешь метод для генерации рандома. По-хорошему, если ты хочешь такие вещи делать, то надо создать свой класс Random и завернуть в него все такие штуки. И уже этот класс рандом сделать статическими данными в классе.
```cpp
class Random {
  public:
    Vector getUniformVector(double low, double high) const;
    // И уже внутри этого метода делаешь все настройки.
  private:
  Eigen::Rand::Vmt19937_64 urng{42};
};
```

2024-01-13 17:41 UTC, DimaTrushin commented on NeuralNetwork/linear.cpp
> +    }
Это нужно завернуть в метод инициализации. Например так
```cpp
Vector getInitialBias(bool bias) {
  if (bias)
    return  Random.getUniformVector(..., ...)
  return Vector();
}
```

2024-01-13 17:41 UTC, DimaTrushin commented on NeuralNetwork/linear.cpp
> +    weight_ = gen.generate<Tensor2D>(in_features, out_features, urng);
Это тоже надо перенести в список инициализации. По сути у Random надо сделать метод getUniformMatrix

2024-01-13 17:41 UTC, DimaTrushin commented on NeuralNetwork/linear.cpp
> +Linear::Tensor2D Linear::operator()(Linear::Tensor2D x) {
Несколько проблем
1) Метод должен быть const
2) У тебя нет смысла принимать аргумент by value. Это дорого и ты не переиспользуешь его память. Потому это не sink argument. А значит надо принимать по константной ссылке. Переделай.

2024-01-13 17:41 UTC, DimaTrushin commented on NeuralNetwork/linear.cpp
> +    }
Нарушение уровня абстракции. Нахуя, а главное зачем? Почему ты не можешь просто взять и использовать матричные операции? Вырази все через матричные операции умножения, сложения, транспонирования и т.д.

2024-01-13 17:41 UTC, DimaTrushin commented on NeuralNetwork/linear.cpp
> +void Linear::Update(Linear::Tensor2D u) {
Если этот метод обнавляет параметры, то может быть имеет смысл сразу же из него возвращать новый u для следующего слоя? Потому что его все равно надо считать по значениям параметров до обновления и будет проще так работать со слоями.

2024-01-13 17:41 UTC, DimaTrushin commented on NeuralNetwork/linear.cpp
> +    //// Needs to be done before weight updating or not?
Да, это правильная мысль. Потому я предлагаю объединить эти два метода.

2024-01-13 17:41 UTC, DimaTrushin commented on NeuralNetwork/linear.cpp
> +    bias_ -= bias_grad_;
Тебе не хватает параметра -- длина шага.

2024-01-20 13:00 UTC, DimaTrushin requested changes
Сделал несколько мелких замечаний.

2024-01-20 13:00 UTC, DimaTrushin commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD_REQUIRED ON)
Я привык видеть эту строчку после задания стандарта. Надо бы погуглить есть ли разница. Микрозадание для Гоши =)

2024-01-20 13:00 UTC, DimaTrushin commented on NeuralNetwork/neuraldefines.h
> +class NeuralDefines {
Сделай эту штуку публичной структурой и сделай все дефайны публичными. Потому что ты потом в тестах используешь эти типы и вместо того, чтобы брать их отсюда, ты их заново переопределяешь. Это ломает все зависимости и локальность. Если ты захочешь что-то поменять тут, тебе придется менять и в тестах.

2024-01-20 13:00 UTC, DimaTrushin commented on NeuralNetwork/tests/test_activation.cpp
> +using Tensor3D = std::vector<Tensor2D>;
Тягай эти юзинги напрямую из твоего neuraldefines.h и не определяй заново.

2024-01-20 13:00 UTC, DimaTrushin commented on NeuralNetwork/loss.h
> +    Tensor2D CalculateGradient();
1) Оба метода должны быть константными.
2) Почему второй метод не принимает аргументы? Это очень странно.
3) Если добавляешь методы в класс, то добавляй хотя бы тупую имплементацию, чтобы не было ошибки линковки во время сборки проекта.

2024-01-20 13:00 UTC, DimaTrushin commented on NeuralNetwork/linear.h
> +    Linear(int64_t in_features, int64_t out_features, bool enable_bias = true);
Не используй сырые типы. Ты же уже включил using Index = Eigen::Index; Используй всегда только осмысленный тип.

2024-01-20 13:00 UTC, DimaTrushin commented on NeuralNetwork/linear.h
> +    Linear(int64_t in_features, int64_t out_features, bool enable_bias = true);
Почему остался булев флаг? Сравни два следующих вызова
```cpp
Layer l(4, 5, true);
Layer l(4, 5, Bias::Enable);
```
Второй вариант сильно лучше. То есть надо сделать enum class Bias или как-то так его назвать по нормальному и вызывать именно так. Кроме того, В твоем конструкторе есть еще один дефект. Пользователь может написать
```cpp
Layer l(true, 4, 5);
```
Это скомпилируется без единого сообщения об ошибке, но получится совершенно НЕ то, что ты ожидаешь. Не надо обманывать пользователя твоего кода. Ему должно быть сложно использовать твой код неправильно. В c++ никогда нельзя забывать о преобразовании встроенных типов друг к другу по умолчанию.

2024-01-20 13:00 UTC, DimaTrushin commented on NeuralNetwork/linear.h
> +    nn_random::Random rng_;
Плохой дизайн рандома. У тебя лишнее данное на его хранения приходится. Хотя он у тебя по сути статический объект. Я бы убрал тут эту штуку.
1) Во-первых, это смущает пользователя. Есть впечатление как будто каждый слой хранит свой собственный рандом, хотя это лишь точка доступа к нему.
2) Во-вторых, рандом надо вызывать внутри методов через статические методы или через объекты доступа к нему. Но не тут. Я прокомментирую рандом как его поправить.

2024-01-20 13:00 UTC, DimaTrushin commented on NeuralNetwork/random.h
> +    inline static Eigen::Rand::Vmt19937_64 urng{42};
Заверни в Scott Meyers Singleton так
```cpp
using Generator64 = Eigen::Rand::Vmt19937_64;
static Generator64& generator() {
  static Generator64 rng = 42;
  return rng;
}
```

2024-01-20 13:00 UTC, DimaTrushin commented on NeuralNetwork/random.h
> +    Tensor2D GetUniformMatrix(double low, double high, Index rows, Index cols) const;
Сделай методы static. Они у тебя зависят только от класса, но не от instance объекта класса.

2024-01-20 13:00 UTC, DimaTrushin commented on NeuralNetwork/random.cpp
> +    // TODO: function needs refactoring, because can only generate in [-1; 1]
because it only can generate

2024-01-20 13:00 UTC, DimaTrushin commented on NeuralNetwork/random.cpp
> +    Eigen::Rand::UniformRealGen gen(low, high);
Я что-то не нашел такого конструктора у этого класса. Надо разобраться, что не так.

2024-01-20 13:00 UTC, DimaTrushin commented on NeuralNetwork/sequential.h
> +    std::tuple<Args...> network_;
Лучше сказать layers_ потому что слои могут не быть нейросетями.

2024-01-20 13:00 UTC, DimaTrushin commented on NeuralNetwork/tests/test_activation.cpp
> +    }
Нарушение уровня абстракции, тут должно быть
```cpp
REQUIRE(isZeroMatrix(out));
// или
REQUIRE(out == Matrix::ZeroMatrix());
```
или что-то в этом духе.

2024-01-20 13:00 UTC, DimaTrushin commented on NeuralNetwork/tests/test_activation.cpp
> +    const double v = -10.0;
constexpr

2024-01-20 13:00 UTC, DimaTrushin commented on NeuralNetwork/tests/test_activation.cpp
> +    const double v = -10.0;
Я бы все константы выносил в начало теста в виде constexpr выражений. А вообще можно тест прогонять со случайными константами и тогда смотреть не упадет ли ничего.

2024-01-20 13:00 UTC, DimaTrushin commented on NeuralNetwork/tests/test_random.cpp
> +                for (auto j : gen.row(i)) {
Ну комон, 5 вложенных scope! Даже в ядре Linux запрещено больше 3.

2024-01-20 13:13 UTC, georgyshamteev commented on NeuralNetwork/linear.h
> +    Linear(int64_t in_features, int64_t out_features, bool enable_bias = true);
Отвечу по поводу этого сразу. Это было осмысленное действие. Пользователь зовет слой так:
nn::Linear(10, 20) условно. Инты в Eigen::Index не конвертятся никак. Если ты проверишь ты это увидишь. У меня был изначально конструктор от Inex in_features и оно просто не компилилось

2024-01-20 13:14 UTC, georgyshamteev commented on NeuralNetwork/linear.h
> +    Linear(int64_t in_features, int64_t out_features, bool enable_bias = true);
Не успел поменять просто еще. Сори.

2024-01-20 13:20 UTC, georgyshamteev commented on NeuralNetwork/linear.h
> +    Linear(int64_t in_features, int64_t out_features, bool enable_bias = true);
Ладно, отмена. Когад я тестил в прошлый раз оно почему-то не хотело компилиться, тогда я убрал Eigen::Index на int и заработало. Щас вернул Index обратно и теперь работает. Почему так я хз, но пофиксил проблему. Спс

2024-04-15 14:40 UTC, afigor2701 commented on NeuralNetwork/loss.cpp
> +    return static_cast<double>(1) / y.rows() * loss_(x, y);
ты долбаеб? loss_(x, y) / y.rows()

2024-04-15 14:51 UTC, afigor2701 commented on NeuralNetwork/loss.cpp
> +    : loss_(loss), grad_(grad) {
std::move?

2024-04-15 15:00 UTC, afigor2701 commented on NeuralNetwork/AnyLayer.h
> +        Tensor2D Update(Tensor2D &u) override {
const?

2024-04-15 15:02 UTC, afigor2701 commented on NeuralNetwork/random.cpp
> +    return gen.generate<Tensor1D>(1, cols, Gen()) / 10;
ууууу magic numbers. акос прошел мимо

2024-09-05 09:03 UTC, merged